Support invisible columns in the new AOSC parser
Summary:
invisible column is a new mysql 8.0 feature and more and more internal customers start using that.

Lack of invisible column support also caused exceptions in aosc_local_checksum, which also blocked the fb_dba_osc rpm to release.

```
[xdb0301.cln6.facebook.com] [Thu Aug 08 21:43:35 2024] [aosc_local_checksum] osc.lib.sqlparse.create.ParseError: Unsupported column attribute VISIBILITY_COLUMN_ATTR
(argv: ['/usr/local/bin/aosc_local_checksum'])
(cwd: '/')
(unixname: 'root')

Traceback (most recent call last):
  File "dba/osc/core/lib/ast_parser/fb_ast_parser_lib.pyx", line 237, in dba.osc.core.lib.ast_parser.fb_ast_parser_lib.AstCreateParser.decode_col_attr
osc.lib.sqlparse.create.ParseError: Unsupported column attribute VISIBILITY_COLUMN_ATTR
```

Reviewed By: preritj24

Differential Revision: D61033775

fbshipit-source-id: 85b566bada45d2db03f2a0ae88ef3ce7989d321c