Fix bug when using boolean instead of bool
Summary:
When `BOOLEAN` is used instead of `BOOL` it was detecting `BOOL` and identifying the next part (`EAN`) as a wrong token. Fix by evaluating `BOOLEAN` first.

```
ParseError: Line: `is_used` BOOLEAN DEFAULT FALSE,, Column: 15
 Failed to parse SQL, unsupported syntax: Expected ")", found 'E'  (at char 305), (line:8, col:15)
```

Differential Revision: D30408473

fbshipit-source-id: eea2cb5802fa8ba5828f03731b52d0cb0ce57a1c